version: '3.8'
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: 'catalog-service:0.0.1-SNAPSHOT'
    container_name: 'catalog-service'
    ports:
      - '9001:9001'
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
  polar-postgres:
    image: "postgres:15.2"
    container_name: "polar-postgres"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=polardb_catalog
