CREATE TABLE book
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn       VARCHAR(255),
    title      VARCHAR(255),
    author     VARCHAR(255),
    price      DOUBLE PRECISION                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version    INTEGER                                 NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE INDEX idx_book_id ON book (id);
